complie:
	gcc -o ei -I/usr/local/opt/erlang/lib/erlang/lib/erl_interface-3.9.2/include -L/usr/local/opt/erlang/lib/erlang/lib/erl_interface-3.9.2/lib comm.c ei.c -lerl_interface -lei

clean:
	rm -rf ei *.beam

