PROJECT = websocket
PROJECT_DESCRIPTION = Cowboy Websocket example
PROJECT_VERSION = 1
#PROJECT_ENV = {mnesia, {dir, ""}}
#PROJECT_APP_EXTRA_KEYS = {key, {k1, v1}}

LOCAL_DEPS = sasl,mnesia,observer,wx,runtime_tools
DEPS = cowboy
dep_cowboy_commit = master

include erlang.mk
